project:
  output-dir: "manuscript"
  execute-dir: file
  render: 
    - scripts/0_main.qmd
execute: 
  echo: false
  warning: false
  
format: 
  pdf:
    # titlepage
    title: "Assessing Publication Bias in Meta-Analyses:"
    subtitle: "A Simulation-Based Estimation Approach Focusing on the Joint Distribution of Effect Size and Sample Size"
    author: "Jan Luca Schnatz"
    email: "janluca.schnatz@gmx.de"
    student-id: "7516898"
    affilitation: Abteilung f체r Psychologische Methoden mit Interdisziplin채rer Ausrichtung
    department: "Institut f체r Psychologie und Sportwissenschaften" 
    university: Goethe-Universit채t Frankfurt am Main
    promotor: Prof. Dr. Martin Schultze
    copromotor: Julia Beitner, M.Sc.
    due-date: "21. Mai 2024"
    
    # document settings
    documentclass: scrartcl
    classoption: twoside      
    geometry:
      - inner=3.5cm
      - outer=2.5cm
      - top=2.5cm
      - bottom=3.5cm
    link-citations : true
    urlcolor       : black
    linkcolor      : black
    fontsize       : 12pt
    toc: false
    fig-align: center
    fig-cap-location: top
    bibliography: bibliography/tidy_references.bib
    csl: apa.csl
    citecolor: black
    cite-method: citeproc
    link-citation: true
    engine: knitr
    zotero: true
    keep-tex: false
    include-in-header: tex/header.tex
    template-partials: 
      - tex/before-body.tex 