project:
  output-dir: "_manuscript"
  execute-dir: project
  render: 
    - scripts/0_main.qmd
format: 
  pdf:
    title: "Assessing Publication Bias in Meta-Analyses:"
    subtitle: "A Simulation-Based Estimation Approach Focusing on the Joint Distribution of Effect Size and Sample Size"
    author:
    - name: "Jan Luca Schnatz"
      email: "janluca.schnatz@gmx.de"
      acknowledgements: "7516898"       # Student ID 
      phone: "Julia Beitner M.Sc."      # Second Supervisor
      fax: "Prof. Dr. Martin Schultze"  # First Supervisor
      affiliations:
      - name: Goethe-Universität Frankfurt am Main
        department: "Faculty 05: Psychology and Sports Sciences" 
        city: "Department of Psychological Methods with Interdisciplinary Focus"
    documentclass: scrartcl
    include-in-header: _tex/header.tex
    template-partials: 
      - _tex/before-body.tex 
    link-citations : true
    urlcolor       : black
    linkcolor      : black
    fontsize       : 12pt
    toc: false
    fig-align: center
    fig-cap-location: top
    bibliography: references.bib
    csl: apa.csl
    citecolor: black
    #mainfont: CMU Bright
    #mathfont: CMU Serif
    




