project:
  output-dir: "manuscript"
  execute-dir: project
  render: 
    - scripts/0_main.qmd
execute: 
  cache: true
  echo: false
  warning: false
format: 
  pdf:
    # titlepage
    title: "Assessing Publication Bias in Meta-Analyses:"
    subtitle: "A Simulation-Based Estimation Approach Focusing on the Joint Distribution of Effect Size and Sample Size"
    author: "Jan Luca Schnatz"
    email: "janluca.schnatz@gmx.de"
    student-id: "7516898"
    affilitation: Department of Psychological Methods with Interdisciplinary Focus 
    department: "Faculty 05: Psychology and Sports Sciences" 
    university: Goethe-Universität Frankfurt am Main
    promotor: Prof. Dr. Martin Schultze
    copromotor: Julia Beitner M.Sc.
    date: today
    date-format: "MMMM, YYYY"

    # document settings
    documentclass: scrartcl
    classoption: twoside      
    geometry:
      - inner=2.5cm
      - outer=3.5cm
      - top=2.5cm
      - bottom=3.5cm
      #- headsep=22pt
      #- headheight=11pt
      #- footskip=33pt
      #- ignorehead
      #- ignorefoot
      #- heightrounded
    link-citations : true
    urlcolor       : black
    linkcolor      : black
    fontsize       : 12pt
    toc: false
    fig-align: center
    fig-cap-location: top
    bibliography: bibliography/tidy_references.bib
    csl: apa.csl
    citecolor: black
    #margin-left: 2.5cm
    #margin-right: 2.5cm
    #margin-top: 2.5cm
    #margin-bottom: 2cm
    cite-method: biblatex
    link-citation: true
    engine: knitr
    zotero: true
    include-in-header: tex/header.tex
    template-partials: 
      - tex/before-body.tex 